GET  http://localhost:3000/api/usuarios HTTP/1.1
###


POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
    
    "name":"grog",
    "username":"miguel",
    
    "pass":"3873356180"
}

###

###

DELETE  http://localhost:3000/30 HTTP/1.1
Content-Type: application/json

###
PUT  http://localhost:3000/30 HTTP/1.1
Content-Type: application/json

{
    
    "name": "miguel",
    "username":"manuel",
    "pass":"12345"
}






//////query grupos
###
GET  http://localhost:3000/api/grupos HTTP/1.1
###
POST http://localhost:3000/grupos HTTP/1.1
Content-Type: application/json

{
    
    "nombre":"eduardo",
    "encargado":"yanno",
    "lugar":"mosconi",
    "contacto":"12345",
    "img":"algo mu bueno esta por empesar"
}

###
DELETE  http://localhost:3000/grupos/7 HTTP/1.1
Content-Type: application/json
###

PUT  http://localhost:3000/api/grupos/5 HTTP/1.1
Content-Type: application/json

{
    
    "nombre":"eduardo",
    "encargado":"yanno",
    "lugar":"mosconi",
    "contacto":"12345",
    "img":"algo mu bueno esta por empesar"
    
}


// posteo de noticias
###
GET  http://localhost:3000/api/vnoticias HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3000/noticias HTTP/1.1
Content-Type: application/json

{
    
   "titulo":"Gran partido voley",
   "img": "Tampoco",
   "cerpo":"no existe"
}

###

DELETE  http://localhost:3000/noticias/4 HTTP/1.1
Content-Type: application/json